# Generated by Django 5.1.1 on 2025-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_frontenduser_correct_problems"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconversation",
            name="precursor_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
