# Generated by Django 5.1.1 on 2025-03-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userconversation_precursor_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AddField(
            model_name="problem",
            name="categories",
            field=models.ManyToManyField(to="users.category"),
        ),
        migrations.AddField(
            model_name="problem",
            name="type",
            field=models.CharField(
                choices=[("single", "单选"), ("multiple", "多选")],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="problem",
            name="exam_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="users.examset",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="question_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
