# Generated by Django 5.1.1 on 2025-03-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_textcontent_video_recommendationcontent_userfavorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textcontent",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "topic"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.category",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "topic"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.category",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
