# Generated by Django 5.1.1 on 2025-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_textcontent_topic_video_topic_alter_video_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="bvid",
            field=models.CharField(max_length=20),
        ),
    ]
