# Generated by Django 5.1.1 on 2025-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_video_bvid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendationcontent",
            old_name="content_id",
            new_name="content_key",
        ),
        migrations.RenameField(
            model_name="userfavorite",
            old_name="content_id",
            new_name="content_key",
        ),
        migrations.AddField(
            model_name="recommendationcontent",
            name="p",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationcontent",
            name="content_type",
            field=models.CharField(
                choices=[("video", "视频"), ("text", "图文")], max_length=10
            ),
        ),
    ]
