# Generated by Django 5.1.1 on 2025-03-27 14:07

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_content_id_recommendationcontent_content_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLearningBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_frequency_last_7_days", models.JSONField(default=dict)),
                ("topic_proficiency", models.JSONField(default=dict)),
                (
                    "active_time_counts",
                    models.JSONField(default=users.models.default_active_time_counts),
                ),
                ("active_time_distribution", models.JSONField(default=dict)),
                (
                    "last_learning_time_interval",
                    models.CharField(
                        choices=[
                            ("1h", "1小时内"),
                            ("1d", "1天内"),
                            ("1w", "1周内"),
                            ("1m", "1月内"),
                            ("long", "1个月以上"),
                        ],
                        default="long",
                        max_length=5,
                    ),
                ),
                ("content_click_rate", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.frontenduser",
                    ),
                ),
            ],
        ),
    ]
