# Generated by Django 5.1.1 on 2025-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userlearningbehavior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlearningbehavior",
            name="last_learning_time_interval",
            field=models.CharField(
                choices=[
                    ("0", "刚刚"),
                    ("1h", "1小时内"),
                    ("1d", "1天内"),
                    ("1w", "1周内"),
                    ("1m", "1月内"),
                    ("long", "1个月以上"),
                ],
                default="long",
                max_length=5,
            ),
        ),
    ]
