# Generated by Django 5.1.1 on 2025-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_userlearningbehavior_last_learning_time_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationcontent",
            name="popularity",
            field=models.FloatField(default=0.0),
        ),
    ]
