# Generated by Django 5.1.1 on 2025-03-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_recommendationcontent_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlearningbehavior",
            name="content_click_count",
            field=models.JSONField(default=dict),
        ),
    ]
