# Generated by Django 5.1.1 on 2025-03-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_userlearningbehavior_content_click_count"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendationscore",
            unique_together={("user", "content")},
        ),
        migrations.AddField(
            model_name="recommendationscore",
            name="content",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.recommendationcontent",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="recommendationscore",
            name="category",
        ),
    ]
