# Generated by Django 5.1.1 on 2025-03-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_recommendationscore_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendationscore",
            unique_together={("user", "content")},
        ),
    ]
