# Generated by Django 5.1.1 on 2025-03-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_recommendationscore_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendationscore",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="recommendationscore",
            index=models.Index(
                fields=["user", "content"], name="users_recom_user_id_e4a180_idx"
            ),
        ),
    ]
