# Generated by Django 5.1.1 on 2025-03-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_recommendationscore_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendationscore",
            name="users_recom_user_id_e4a180_idx",
        ),
        migrations.AlterUniqueTogether(
            name="recommendationscore",
            unique_together={("user", "content")},
        ),
    ]
