# Generated by Django 5.1.1 on 2025-03-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0020_remove_recommendationscore_users_recom_user_id_e4a180_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecommendationScore",
        ),
    ]
