# Generated by Django 5.1.1 on 2025-03-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_recommendationscore"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecommendationScore",
        ),
    ]
