# Generated by Django 5.1.1 on 2025-03-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_delete_recommendationscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.recommendationcontent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.frontenduser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "content")},
            },
        ),
    ]
