# Generated by Django 5.1.1 on 2025-03-31 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_userrating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfavorite",
            unique_together={("user", "content")},
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="content",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.recommendationcontent",
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("tencent", "腾讯地图 API"),
                    ("tianditu", "天地图 API"),
                    ("baidu", "百度百科 API"),
                    ("deepseek", "DeepSeek API"),
                    ("xfyun", "讯飞星火 API"),
                    ("trefle", "trefle 植物百科 API"),
                    ("custom", "自定义 API"),
                ],
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="userfavorite",
            name="content_key",
        ),
        migrations.RemoveField(
            model_name="userfavorite",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="userfavorite",
            name="p",
        ),
    ]
