# Generated by Django 5.1.1 on 2025-03-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_userfavorite_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFavorite",
        ),
    ]
