# Generated by Django 5.1.1 on 2025-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_userfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationcontent",
            name="total_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendationcontent",
            name="weekly_clicks",
            field=models.JSONField(default=dict),
        ),
    ]
