# Generated by Django 5.1.1 on 2025-04-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_recommendationcontent_total_clicks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationcontent",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "topic"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.category",
            ),
        ),
    ]
