# Generated by Django 5.1.1 on 2025-04-16 11:00

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_recommendationcontent_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConversationHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precursor_id", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_message", models.TextField()),
                ("llm_summary", models.TextField(blank=True, null=True)),
                (
                    "frontend_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.frontenduser",
                    ),
                ),
                (
                    "model_config",
                    models.ForeignKey(
                        default=users.models.get_default_deepseek_config,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.apiconfig",
                    ),
                ),
            ],
        ),
    ]
