# Generated by Django 5.1.1 on 2025-04-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_userconversationheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconversationheader",
            name="model_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.apiconfig",
            ),
        ),
    ]
