# Generated by Django 5.1.1 on 2025-05-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconversationheader",
            name="source",
            field=models.CharField(default="world_map", max_length=100),
        ),
    ]
