# Generated by Django 5.1.1 on 2025-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_userconversationheader_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconversation",
            name="topic_relationship",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category_type": "topic"},
                to="users.category",
            ),
        ),
    ]
